# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konfig < Formula
  desc ""
  homepage "https://github.com/ppcool1163/konfig"
  version "0.2"

  on_macos do
    url "https://github.com/ppcool1163/konfig/releases/download/v0.2/konfig_0.2_darwin_all.tar.gz"
    sha256 "0d3fed7e76ebda868c33ee4daca4e84a3015e06a11823243ac39850a68b2bff7"

    def install
      bin.install "konfig"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ppcool1163/konfig/releases/download/v0.2/konfig_0.2_linux_arm64.tar.gz"
      sha256 "3d2d8b8c3a54ef26653b6b9ab1798a6cebc91fca85ec0eb03c3f287afc83d818"

      def install
        bin.install "konfig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ppcool1163/konfig/releases/download/v0.2/konfig_0.2_linux_amd64.tar.gz"
      sha256 "13cc187a4dc17ad9922f5fed68e772a08b140af216f3d164a4003efb18756704"

      def install
        bin.install "konfig"
      end
    end
  end
end
